#!/bin/bash
if ! lsb_release -r | grep -q '^Release.*12\.04'; then
    echo "The primary build platform is Ubuntu 12.04, if things fail try building there."
    echo -n "Enter to continue..."
    read
else
    # Move configuration files over to let us get libgoogle-glog-dev and friends
    # from Quantal repos
    sudo rsync -r $(dirname $0)/dependency_files/ /
fi

sudo apt-get update
sudo apt-get install build-essential cmake libboost-dev libprotobuf-dev \
    blktrace subversion libgoogle-glog-dev libgoogle-glog0 \
    nbd-server uuid-dev protobuf-compiler python-protobuf e2fslibs-dev \
    libboost-regex-dev libblkid-dev google-mock
