// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t1.proto

#ifndef PROTOBUF_t1_2eproto__INCLUDED
#define PROTOBUF_t1_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_t1_2eproto();
void protobuf_AssignDesc_t1_2eproto();
void protobuf_ShutdownFile_t1_2eproto();

class TestMessage;

// ===================================================================

class TestMessage : public ::google::protobuf::Message {
 public:
  TestMessage();
  virtual ~TestMessage();
  
  TestMessage(const TestMessage& from);
  
  inline TestMessage& operator=(const TestMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessage& default_instance();
  
  void Swap(TestMessage* other);
  
  // implements Message ----------------------------------------------
  
  TestMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessage& from);
  void MergeFrom(const TestMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string txtmsg = 1;
  inline bool has_txtmsg() const;
  inline void clear_txtmsg();
  static const int kTxtmsgFieldNumber = 1;
  inline const ::std::string& txtmsg() const;
  inline void set_txtmsg(const ::std::string& value);
  inline void set_txtmsg(const char* value);
  inline void set_txtmsg(const char* value, size_t size);
  inline ::std::string* mutable_txtmsg();
  inline ::std::string* release_txtmsg();
  
  // required int64 stamp = 2;
  inline bool has_stamp() const;
  inline void clear_stamp();
  static const int kStampFieldNumber = 2;
  inline ::google::protobuf::int64 stamp() const;
  inline void set_stamp(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:TestMessage)
 private:
  inline void set_has_txtmsg();
  inline void clear_has_txtmsg();
  inline void set_has_stamp();
  inline void clear_has_stamp();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* txtmsg_;
  ::google::protobuf::int64 stamp_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_t1_2eproto();
  friend void protobuf_AssignDesc_t1_2eproto();
  friend void protobuf_ShutdownFile_t1_2eproto();
  
  void InitAsDefaultInstance();
  static TestMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// TestMessage

// required string txtmsg = 1;
inline bool TestMessage::has_txtmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestMessage::set_has_txtmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestMessage::clear_has_txtmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestMessage::clear_txtmsg() {
  if (txtmsg_ != &::google::protobuf::internal::kEmptyString) {
    txtmsg_->clear();
  }
  clear_has_txtmsg();
}
inline const ::std::string& TestMessage::txtmsg() const {
  return *txtmsg_;
}
inline void TestMessage::set_txtmsg(const ::std::string& value) {
  set_has_txtmsg();
  if (txtmsg_ == &::google::protobuf::internal::kEmptyString) {
    txtmsg_ = new ::std::string;
  }
  txtmsg_->assign(value);
}
inline void TestMessage::set_txtmsg(const char* value) {
  set_has_txtmsg();
  if (txtmsg_ == &::google::protobuf::internal::kEmptyString) {
    txtmsg_ = new ::std::string;
  }
  txtmsg_->assign(value);
}
inline void TestMessage::set_txtmsg(const char* value, size_t size) {
  set_has_txtmsg();
  if (txtmsg_ == &::google::protobuf::internal::kEmptyString) {
    txtmsg_ = new ::std::string;
  }
  txtmsg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TestMessage::mutable_txtmsg() {
  set_has_txtmsg();
  if (txtmsg_ == &::google::protobuf::internal::kEmptyString) {
    txtmsg_ = new ::std::string;
  }
  return txtmsg_;
}
inline ::std::string* TestMessage::release_txtmsg() {
  clear_has_txtmsg();
  if (txtmsg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = txtmsg_;
    txtmsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int64 stamp = 2;
inline bool TestMessage::has_stamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestMessage::set_has_stamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestMessage::clear_has_stamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestMessage::clear_stamp() {
  stamp_ = GOOGLE_LONGLONG(0);
  clear_has_stamp();
}
inline ::google::protobuf::int64 TestMessage::stamp() const {
  return stamp_;
}
inline void TestMessage::set_stamp(::google::protobuf::int64 value) {
  set_has_stamp();
  stamp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_t1_2eproto__INCLUDED
