#!/bin/bash

temp_file=$(mktemp /tmp/test_loop_file.XXXXXXXXX)

if [ $# -ne 1 ]; then
  echo "$0: Need one argument"
  echo "$0: $@"
  exit 1
fi

if ! truncate --size=10M "$temp_file"; then
  exit 1
fi

echo "Creating test loop device"
losetup -fv "$temp_file" | tail -n1 | sed -e 's/Loop device is //g' | tr -d '\n' > "$1"

if [ ! -b $(cat "$1") ]; then
  echo "$0: Failed to create loop device"
  exit 1
fi

exit 0
