#!/bin/bash

temp_file=$(mktemp /tmp/test_loop_file.XXXXXXXXX)

if [ $? -ne 0 ]; then
  exit 1
fi

if ! truncate --size=1M "$temp_file"; then
  exit 1
fi

echo "Creating test loop device"
losetup -fv "$temp_file" | tail -n1 | sed -e 's/Loop device is //g' | tr -d '\n' > /dev/shm/test_loop_path

if [ ! -b $(cat /dev/shm/test_loop_path) ]; then
  echo "Failed to create loop device"
  exit 1
fi

exit 0
