// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "base_signature.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace datto_linux_client {

namespace {

const ::google::protobuf::Descriptor* BaseSignature_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BaseSignature_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_base_5fsignature_2eproto() {
  protobuf_AddDesc_base_5fsignature_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "base_signature.proto");
  GOOGLE_CHECK(file != NULL);
  BaseSignature_descriptor_ = file->message_type(0);
  static const int BaseSignature_offsets_[1] = {
  };
  BaseSignature_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BaseSignature_descriptor_,
      BaseSignature::default_instance_,
      BaseSignature_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseSignature, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BaseSignature, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BaseSignature));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_base_5fsignature_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BaseSignature_descriptor_, &BaseSignature::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_base_5fsignature_2eproto() {
  delete BaseSignature::default_instance_;
  delete BaseSignature_reflection_;
}

void protobuf_AddDesc_base_5fsignature_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024base_signature.proto\022\022datto_linux_clie"
    "nt\"\017\n\rBaseSignature", 59);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "base_signature.proto", &protobuf_RegisterTypes);
  BaseSignature::default_instance_ = new BaseSignature();
  BaseSignature::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_base_5fsignature_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_base_5fsignature_2eproto {
  StaticDescriptorInitializer_base_5fsignature_2eproto() {
    protobuf_AddDesc_base_5fsignature_2eproto();
  }
} static_descriptor_initializer_base_5fsignature_2eproto_;


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

BaseSignature::BaseSignature()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BaseSignature::InitAsDefaultInstance() {
}

BaseSignature::BaseSignature(const BaseSignature& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BaseSignature::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BaseSignature::~BaseSignature() {
  SharedDtor();
}

void BaseSignature::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BaseSignature::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BaseSignature::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BaseSignature_descriptor_;
}

const BaseSignature& BaseSignature::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_base_5fsignature_2eproto();  return *default_instance_;
}

BaseSignature* BaseSignature::default_instance_ = NULL;

BaseSignature* BaseSignature::New() const {
  return new BaseSignature;
}

void BaseSignature::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BaseSignature::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void BaseSignature::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BaseSignature::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BaseSignature::ByteSize() const {
  int total_size = 0;
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BaseSignature::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BaseSignature* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BaseSignature*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BaseSignature::MergeFrom(const BaseSignature& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BaseSignature::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BaseSignature::CopyFrom(const BaseSignature& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseSignature::IsInitialized() const {
  
  return true;
}

void BaseSignature::Swap(BaseSignature* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BaseSignature::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BaseSignature_descriptor_;
  metadata.reflection = BaseSignature_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace datto_linux_client

// @@protoc_insertion_point(global_scope)
