// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_signature.proto

#ifndef PROTOBUF_base_5fsignature_2eproto__INCLUDED
#define PROTOBUF_base_5fsignature_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace datto_linux_client {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_base_5fsignature_2eproto();
void protobuf_AssignDesc_base_5fsignature_2eproto();
void protobuf_ShutdownFile_base_5fsignature_2eproto();

class BaseSignature;

// ===================================================================

class BaseSignature : public ::google::protobuf::Message {
 public:
  BaseSignature();
  virtual ~BaseSignature();
  
  BaseSignature(const BaseSignature& from);
  
  inline BaseSignature& operator=(const BaseSignature& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseSignature& default_instance();
  
  void Swap(BaseSignature* other);
  
  // implements Message ----------------------------------------------
  
  BaseSignature* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseSignature& from);
  void MergeFrom(const BaseSignature& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:datto_linux_client.BaseSignature)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_base_5fsignature_2eproto();
  friend void protobuf_AssignDesc_base_5fsignature_2eproto();
  friend void protobuf_ShutdownFile_base_5fsignature_2eproto();
  
  void InitAsDefaultInstance();
  static BaseSignature* default_instance_;
};
// ===================================================================


// ===================================================================

// BaseSignature


// @@protoc_insertion_point(namespace_scope)

}  // namespace datto_linux_client

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_base_5fsignature_2eproto__INCLUDED
