base_signature.pb.o: base_signature.pb.cc
	g++ -std=c++11 -c -o base_signature.pb.o -I . base_signature.pb.cc -l protobuf -pthread
request.pb.o: request.pb.cc
	g++ -std=c++11 -c -o request.pb.o -I . request.pb.cc -l protobuf -pthread
start_backup_request.pb.o: start_backup_request.pb.cc
	g++ -std=c++11 -c -o start_backup_request.pb.o -I . start_backup_request.pb.cc -l protobuf -pthread
stop_backup_request.pb.o: stop_backup_request.pb.cc
	g++ -std=c++11 -c -o stop_backup_request.pb.o -I . stop_backup_request.pb.cc -l protobuf -pthread
