// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: start_backup_request.proto

#ifndef PROTOBUF_start_5fbackup_5frequest_2eproto__INCLUDED
#define PROTOBUF_start_5fbackup_5frequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "base_signature.pb.h"
// @@protoc_insertion_point(includes)

namespace datto_linux_client {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_start_5fbackup_5frequest_2eproto();
void protobuf_AssignDesc_start_5fbackup_5frequest_2eproto();
void protobuf_ShutdownFile_start_5fbackup_5frequest_2eproto();

class StartBackupRequest;

enum StartBackupRequest_BackupType {
  StartBackupRequest_BackupType_FULL_BACKUP = 1,
  StartBackupRequest_BackupType_INCREMENTAL_BACKUP = 2,
  StartBackupRequest_BackupType_DIFF_BACKUP = 3
};
bool StartBackupRequest_BackupType_IsValid(int value);
const StartBackupRequest_BackupType StartBackupRequest_BackupType_BackupType_MIN = StartBackupRequest_BackupType_FULL_BACKUP;
const StartBackupRequest_BackupType StartBackupRequest_BackupType_BackupType_MAX = StartBackupRequest_BackupType_DIFF_BACKUP;
const int StartBackupRequest_BackupType_BackupType_ARRAYSIZE = StartBackupRequest_BackupType_BackupType_MAX + 1;

const ::google::protobuf::EnumDescriptor* StartBackupRequest_BackupType_descriptor();
inline const ::std::string& StartBackupRequest_BackupType_Name(StartBackupRequest_BackupType value) {
  return ::google::protobuf::internal::NameOfEnum(
    StartBackupRequest_BackupType_descriptor(), value);
}
inline bool StartBackupRequest_BackupType_Parse(
    const ::std::string& name, StartBackupRequest_BackupType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StartBackupRequest_BackupType>(
    StartBackupRequest_BackupType_descriptor(), name, value);
}
// ===================================================================

class StartBackupRequest : public ::google::protobuf::Message {
 public:
  StartBackupRequest();
  virtual ~StartBackupRequest();
  
  StartBackupRequest(const StartBackupRequest& from);
  
  inline StartBackupRequest& operator=(const StartBackupRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const StartBackupRequest& default_instance();
  
  void Swap(StartBackupRequest* other);
  
  // implements Message ----------------------------------------------
  
  StartBackupRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartBackupRequest& from);
  void MergeFrom(const StartBackupRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef StartBackupRequest_BackupType BackupType;
  static const BackupType FULL_BACKUP = StartBackupRequest_BackupType_FULL_BACKUP;
  static const BackupType INCREMENTAL_BACKUP = StartBackupRequest_BackupType_INCREMENTAL_BACKUP;
  static const BackupType DIFF_BACKUP = StartBackupRequest_BackupType_DIFF_BACKUP;
  static inline bool BackupType_IsValid(int value) {
    return StartBackupRequest_BackupType_IsValid(value);
  }
  static const BackupType BackupType_MIN =
    StartBackupRequest_BackupType_BackupType_MIN;
  static const BackupType BackupType_MAX =
    StartBackupRequest_BackupType_BackupType_MAX;
  static const int BackupType_ARRAYSIZE =
    StartBackupRequest_BackupType_BackupType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  BackupType_descriptor() {
    return StartBackupRequest_BackupType_descriptor();
  }
  static inline const ::std::string& BackupType_Name(BackupType value) {
    return StartBackupRequest_BackupType_Name(value);
  }
  static inline bool BackupType_Parse(const ::std::string& name,
      BackupType* value) {
    return StartBackupRequest_BackupType_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required string block_path = 1;
  inline bool has_block_path() const;
  inline void clear_block_path();
  static const int kBlockPathFieldNumber = 1;
  inline const ::std::string& block_path() const;
  inline void set_block_path(const ::std::string& value);
  inline void set_block_path(const char* value);
  inline void set_block_path(const char* value, size_t size);
  inline ::std::string* mutable_block_path();
  inline ::std::string* release_block_path();
  
  // required .datto_linux_client.StartBackupRequest.BackupType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::datto_linux_client::StartBackupRequest_BackupType type() const;
  inline void set_type(::datto_linux_client::StartBackupRequest_BackupType value);
  
  // optional .datto_linux_client.BaseSignature base_signature = 3;
  inline bool has_base_signature() const;
  inline void clear_base_signature();
  static const int kBaseSignatureFieldNumber = 3;
  inline const ::datto_linux_client::BaseSignature& base_signature() const;
  inline ::datto_linux_client::BaseSignature* mutable_base_signature();
  inline ::datto_linux_client::BaseSignature* release_base_signature();
  
  // @@protoc_insertion_point(class_scope:datto_linux_client.StartBackupRequest)
 private:
  inline void set_has_block_path();
  inline void clear_has_block_path();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_base_signature();
  inline void clear_has_base_signature();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* block_path_;
  ::datto_linux_client::BaseSignature* base_signature_;
  int type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_start_5fbackup_5frequest_2eproto();
  friend void protobuf_AssignDesc_start_5fbackup_5frequest_2eproto();
  friend void protobuf_ShutdownFile_start_5fbackup_5frequest_2eproto();
  
  void InitAsDefaultInstance();
  static StartBackupRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// StartBackupRequest

// required string block_path = 1;
inline bool StartBackupRequest::has_block_path() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StartBackupRequest::set_has_block_path() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StartBackupRequest::clear_has_block_path() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StartBackupRequest::clear_block_path() {
  if (block_path_ != &::google::protobuf::internal::kEmptyString) {
    block_path_->clear();
  }
  clear_has_block_path();
}
inline const ::std::string& StartBackupRequest::block_path() const {
  return *block_path_;
}
inline void StartBackupRequest::set_block_path(const ::std::string& value) {
  set_has_block_path();
  if (block_path_ == &::google::protobuf::internal::kEmptyString) {
    block_path_ = new ::std::string;
  }
  block_path_->assign(value);
}
inline void StartBackupRequest::set_block_path(const char* value) {
  set_has_block_path();
  if (block_path_ == &::google::protobuf::internal::kEmptyString) {
    block_path_ = new ::std::string;
  }
  block_path_->assign(value);
}
inline void StartBackupRequest::set_block_path(const char* value, size_t size) {
  set_has_block_path();
  if (block_path_ == &::google::protobuf::internal::kEmptyString) {
    block_path_ = new ::std::string;
  }
  block_path_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StartBackupRequest::mutable_block_path() {
  set_has_block_path();
  if (block_path_ == &::google::protobuf::internal::kEmptyString) {
    block_path_ = new ::std::string;
  }
  return block_path_;
}
inline ::std::string* StartBackupRequest::release_block_path() {
  clear_has_block_path();
  if (block_path_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = block_path_;
    block_path_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required .datto_linux_client.StartBackupRequest.BackupType type = 2;
inline bool StartBackupRequest::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StartBackupRequest::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StartBackupRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StartBackupRequest::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::datto_linux_client::StartBackupRequest_BackupType StartBackupRequest::type() const {
  return static_cast< ::datto_linux_client::StartBackupRequest_BackupType >(type_);
}
inline void StartBackupRequest::set_type(::datto_linux_client::StartBackupRequest_BackupType value) {
  GOOGLE_DCHECK(::datto_linux_client::StartBackupRequest_BackupType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .datto_linux_client.BaseSignature base_signature = 3;
inline bool StartBackupRequest::has_base_signature() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StartBackupRequest::set_has_base_signature() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StartBackupRequest::clear_has_base_signature() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StartBackupRequest::clear_base_signature() {
  if (base_signature_ != NULL) base_signature_->::datto_linux_client::BaseSignature::Clear();
  clear_has_base_signature();
}
inline const ::datto_linux_client::BaseSignature& StartBackupRequest::base_signature() const {
  return base_signature_ != NULL ? *base_signature_ : *default_instance_->base_signature_;
}
inline ::datto_linux_client::BaseSignature* StartBackupRequest::mutable_base_signature() {
  set_has_base_signature();
  if (base_signature_ == NULL) base_signature_ = new ::datto_linux_client::BaseSignature;
  return base_signature_;
}
inline ::datto_linux_client::BaseSignature* StartBackupRequest::release_base_signature() {
  clear_has_base_signature();
  ::datto_linux_client::BaseSignature* temp = base_signature_;
  base_signature_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace datto_linux_client

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::datto_linux_client::StartBackupRequest_BackupType>() {
  return ::datto_linux_client::StartBackupRequest_BackupType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_start_5fbackup_5frequest_2eproto__INCLUDED
