#!/bin/bash
build_type=${1:-release}
mkdir -p build
cd build

if [ "$build_type" = "debug" ]; then
    min_level=0
else
    min_level=2
fi

GLOG_minloglevel=${min_level} cmake -DCMAKE_BUILD_TYPE=${build_type} .. && make -j4 -k dattod dattocli dattonet

if [ $? -eq 0 ]; then
    echo
    echo "** All files built in ./build **"
fi

