#!/usr/bin/env python

import os
import socket
from start_backup_request_pb2 import StartBackupRequest
from progress_backup_request_pb2 import ProgressBackupRequest
from stop_backup_request_pb2 import StopBackupRequest
from request_pb2 import Request
from string_reply_pb2 import StringReply

IPC_SOCKET_PATH = "/var/datto/dattod_ipc"

def main():
    print 'Starting test server'
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.bind(IPC_SOCKET_PATH)
    s.listen(1)
    conn, addr = s.accept()

    reply = StringReply()
    reply.message = 'Hello World!'
    while True:
        data = conn.recv(1024)
        if not data:
            break
        else:
            request = StartBackupRequest() #How do I identify which one?
            request.ParseFromString(data)
            print request
            conn.send(reply.SerializeToString())
    s.close()
    os.remove(IPC_SOCKET_PATH)

if __name__ == "__main__":
    main()
