#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "usage: $0 block_dev ext2|ext3|ext4|xfs"
    exit 1
fi

part_out=$(partclone."$2" -D -s "$1" 2>/tmp/partclone_error)
if [ $? -ne 0 ]; then
    cat /tmp/partclone_error
    rm /tmp/partclone_error
    exit 1
fi
rm /tmp/partclone_error

OLDIFS=$IFS
IFS=$'\n'
for line in $part_out; do
    if [[ $line == \#* ]]; then
        continue
    fi

    if [[ $line == *\? ]]; then
        continue
    fi

    echo "$line" | sed 's/^\(0x[0-9A-F]*\) *\(0x[0-9A-F]*\).*$/\1 \2/g'
done
IFS=$OLDIFS
