#! /bin/sh
#
# start/stop dattod backup server

### BEGIN INIT INFO
# Provides:          dattod
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the dattod backup server
# Description:       Start the dattod backup server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/dattod
NAME=dattod
PIDFILE=/var/run/dattod.pid

. /lib/lsb/init-functions

set -e

test -x $DAEMON || exit 1

case "$1" in
  start)
	log_daemon_msg "Starting $NAME\t"
	start-stop-daemon --start --oknodo --pidfile $PIDFILE --exec $DAEMON
	log_end_msg $?
	;;

  stop)
	log_daemon_msg "Stopping $NAME\t"
	# Wait 20 seconds for it to die before returning 2
	start-stop-daemon --stop --retry=TERM/20 --oknodo --pidfile $PIDFILE --exec $DAEMON
	# TODO: Decide if we want this force stop here
	if [ $? -eq 2 ]; then
		# start-stop-daemon --stop --signal=KILL --oknodo --pidfile $PIDFILE --exec $DAEMON
		# Force unfreeze everything
		# echo 'j' > /proc/sysrq-trigger
		:
	fi
	rm -f $PIDFILE
	log_end_msg $?
	;;

  restart)
	$0 stop
	sleep 1
	$0 start
	;;

  force-reload)
	if start-stop-daemon --stop --test --quiet --pidfile $PIDFILE --exec $DAEMON; then
		$0 restart
	fi
	;;

  status)
	status_of_proc $DAEMON $NAME && exit 0 || exit $?
	;;

  *)
	log_success_msg "Usage: /etc/init.d/dattod {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
